### ISSUE TITLE
linux build instructions?

### ISSUE THREAD

**Issue by ryanfantus** [ademko/EDandD#1]
Hi, would it be possible to see whether this can build in linux?

**Comment by ademko** [comment]
No, not with a lot of work. It was originally designed to be built with Turbo Pascal under MS-DOS, so a compatible compiler (may free pascal) would need to be used. But that's just the start, some of the libraries would need to be replaced as the program assumes it can do serial communication, so that would need to be redirected to plain Linux streams.
